version: "3.8"

services:
  app:
    container_name: online-store
    build:
      context: .
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"

  postgres:
    container_name: online-store-db
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
