spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=store
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_NULL
mybatis:
  mapper-locations: classpath:mybatis/*.xml
jwt:
  secret:
    key: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w